"""Added estimation log for the sprint

Revision ID: 101e3a4d237
Revises: 8e2197c96c5
Create Date: 2015-08-19 21:38:21.552642

"""

# revision identifiers, used by Alembic.
revision = '101e3a4d237'
down_revision = '8e2197c96c5'

from alembic import op
import sqlalchemy as sa


INSERTS = """"""
DELETES = """"""


def iter_statements(stmts):
    for st in [x for x in stmts.split('\n') if x]:
        op.execute(st)


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estimatelog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sprint_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('estimate', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
    iter_statements(INSERTS)


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estimatelog')
    ### end Alembic commands ###
    iter_statements(DELETES)
