"""Added updated and created field to tasks.

Revision ID: 149bf5aa2d9b
Revises: 6419a88a7c1a
Create Date: 2017-01-25 00:03:31.893693

"""

# revision identifiers, used by Alembic.
revision = '149bf5aa2d9b'
down_revision = '6419a88a7c1a'

from alembic import op
import sqlalchemy as sa


INSERTS = """"""
DELETES = """"""


def iter_statements(stmts):
    for st in [x for x in stmts.split('\n') if x]:
        op.execute(st)


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('updated', sa.DateTime(), nullable=True))
    ### end Alembic commands ###
    iter_statements(INSERTS)


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'updated')
    op.drop_column('tasks', 'created')
    ### end Alembic commands ###
    iter_statements(DELETES)
