"""Added nm table to link tasks to sprints.

Revision ID: 2ad4629b8cc5
Revises: 26629884e7e5
Create Date: 2015-05-04 11:25:54.088959

"""

# revision identifiers, used by Alembic.
revision = '2ad4629b8cc5'
down_revision = '26629884e7e5'

from alembic import op
import sqlalchemy as sa


INSERTS = """"""
DELETES = """"""


def iter_statements(stmts):
    for st in [x for x in stmts.split('\n') if x]:
        op.execute(st)


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nm_task_sprints',
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('sprint_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], )
    )
    ### end Alembic commands ###
    iter_statements(INSERTS)


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nm_task_sprints')
    ### end Alembic commands ###
    iter_statements(DELETES)
