"""Link tags to tasks

Revision ID: 3aa28716712b
Revises: 57a92af0d7c6
Create Date: 2015-05-04 09:20:09.457896

"""

# revision identifiers, used by Alembic.
revision = '3aa28716712b'
down_revision = '57a92af0d7c6'

from alembic import op
import sqlalchemy as sa


INSERTS = """"""
DELETES = """"""


def iter_statements(stmts):
    for st in [x for x in stmts.split('\n') if x]:
        op.execute(st)


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nm_task_tags',
    sa.Column('iid', sa.Integer(), nullable=True),
    sa.Column('tid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['iid'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['tid'], ['tags.id'], )
    )
    ### end Alembic commands ###
    iter_statements(INSERTS)


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nm_task_tags')
    ### end Alembic commands ###
    iter_statements(DELETES)
