"""Added table to store the estimate log

Revision ID: 3c122cdb2612
Revises: 2ad4629b8cc5
Create Date: 2015-05-04 16:28:15.833082

"""

# revision identifiers, used by Alembic.
revision = '3c122cdb2612'
down_revision = '2ad4629b8cc5'

from alembic import op
import sqlalchemy as sa


INSERTS = """"""
DELETES = """"""


def iter_statements(stmts):
    for st in [x for x in stmts.split('\n') if x]:
        op.execute(st)


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estimatelog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sprint_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('estimate', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
    iter_statements(INSERTS)


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estimatelog')
    ### end Alembic commands ###
    iter_statements(DELETES)
