"""Added initial fields to the sprint modul

Revision ID: 4697f61e4e1e
Revises: 26629884e7e5
Create Date: 2015-05-04 11:18:14.133316

"""

# revision identifiers, used by Alembic.
revision = '4697f61e4e1e'
down_revision = '26629884e7e5'

from alembic import op
import sqlalchemy as sa


INSERTS = """"""
DELETES = """"""


def iter_statements(stmts):
    for st in [x for x in stmts.split('\n') if x]:
        op.execute(st)


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sprints', sa.Column('end', sa.Date()))
    op.add_column('sprints', sa.Column('start', sa.Date()))
    op.add_column('sprints', sa.Column('strength', sa.Integer()))
    ### end Alembic commands ###
    iter_statements(INSERTS)


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sprints', 'strength')
    op.drop_column('sprints', 'start')
    op.drop_column('sprints', 'end')
    ### end Alembic commands ###
    iter_statements(DELETES)
