"""Added estimate field to task.

Revision ID: 4a01f1a49d11
Revises: 256a53f5b70c
Create Date: 2015-04-29 22:43:24.972017

"""

# revision identifiers, used by Alembic.
revision = '4a01f1a49d11'
down_revision = '256a53f5b70c'

from alembic import op
import sqlalchemy as sa


INSERTS = """"""
DELETES = """"""


def iter_statements(stmts):
    for st in [x for x in stmts.split('\n') if x]:
        op.execute(st)


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('estimate', sa.Integer(), nullable=True))
    ### end Alembic commands ###
    iter_statements(INSERTS)


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'estimate')
    ### end Alembic commands ###
    iter_statements(DELETES)
