"""Added FK to add subtasks to a task

Revision ID: 505d43887a39
Revises: 3c122cdb2612
Create Date: 2015-05-04 21:35:44.197474

"""

# revision identifiers, used by Alembic.
revision = '505d43887a39'
down_revision = '3c122cdb2612'

from alembic import op
import sqlalchemy as sa


INSERTS = """"""
DELETES = """"""


def iter_statements(stmts):
    for st in [x for x in stmts.split('\n') if x]:
        op.execute(st)


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'tasks', ['parent_id'], ['id'])
    ### end Alembic commands ###
    iter_statements(INSERTS)


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'parent_id')
    ### end Alembic commands ###
    iter_statements(DELETES)
