"""Added title and description to the sprint

Revision ID: 51154dafc283
Revises: 530539821085
Create Date: 2015-10-07 20:48:35.281381

"""

# revision identifiers, used by Alembic.
revision = '51154dafc283'
down_revision = '530539821085'

from alembic import op
import sqlalchemy as sa


INSERTS = """"""
DELETES = """"""


def iter_statements(stmts):
    for st in [x for x in stmts.split('\n') if x]:
        op.execute(st)


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sprints', sa.Column('description', sa.String(), nullable=True))
    op.add_column('sprints', sa.Column('title', sa.String(), nullable=True))
    ### end Alembic commands ###
    iter_statements(INSERTS)


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sprints', 'title')
    op.drop_column('sprints', 'description')
    ### end Alembic commands ###
    iter_statements(DELETES)
