"""Set uuid nullable

Revision ID: 530539821085
Revises: 17e484f70dba
Create Date: 2015-10-07 20:46:50.987432

"""

# revision identifiers, used by Alembic.
revision = '530539821085'
down_revision = '17e484f70dba'

from alembic import op
import sqlalchemy as sa


INSERTS = """"""
DELETES = """"""


def iter_statements(stmts):
    for st in [x for x in stmts.split('\n') if x]:
        op.execute(st)


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actions', 'uuid',
               existing_type=sa.CHAR(length=32),
               nullable=True)
    op.alter_column('comments', 'uuid',
               existing_type=sa.CHAR(length=32),
               nullable=True)
    op.alter_column('forms', 'uuid',
               existing_type=sa.CHAR(length=32),
               nullable=True)
    op.alter_column('modules', 'uuid',
               existing_type=sa.CHAR(length=32),
               nullable=True)
    op.alter_column('profiles', 'uuid',
               existing_type=sa.CHAR(length=32),
               nullable=True)
    op.alter_column('roles', 'uuid',
               existing_type=sa.CHAR(length=32),
               nullable=True)
    op.alter_column('sprints', 'uuid',
               existing_type=sa.CHAR(length=32),
               nullable=True)
    op.alter_column('tags', 'uuid',
               existing_type=sa.CHAR(length=32),
               nullable=True)
    op.alter_column('tasks', 'uuid',
               existing_type=sa.CHAR(length=32),
               nullable=True)
    op.alter_column('usergroups', 'uuid',
               existing_type=sa.CHAR(length=32),
               nullable=True)
    op.alter_column('users', 'uuid',
               existing_type=sa.CHAR(length=32),
               nullable=True)
    ### end Alembic commands ###
    iter_statements(INSERTS)


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'uuid',
               existing_type=sa.CHAR(length=32),
               nullable=False)
    op.alter_column('usergroups', 'uuid',
               existing_type=sa.CHAR(length=32),
               nullable=False)
    op.alter_column('tasks', 'uuid',
               existing_type=sa.CHAR(length=32),
               nullable=False)
    op.alter_column('tags', 'uuid',
               existing_type=sa.CHAR(length=32),
               nullable=False)
    op.alter_column('sprints', 'uuid',
               existing_type=sa.CHAR(length=32),
               nullable=False)
    op.alter_column('roles', 'uuid',
               existing_type=sa.CHAR(length=32),
               nullable=False)
    op.alter_column('profiles', 'uuid',
               existing_type=sa.CHAR(length=32),
               nullable=False)
    op.alter_column('modules', 'uuid',
               existing_type=sa.CHAR(length=32),
               nullable=False)
    op.alter_column('forms', 'uuid',
               existing_type=sa.CHAR(length=32),
               nullable=False)
    op.alter_column('comments', 'uuid',
               existing_type=sa.CHAR(length=32),
               nullable=False)
    op.alter_column('actions', 'uuid',
               existing_type=sa.CHAR(length=32),
               nullable=False)
    ### end Alembic commands ###
    iter_statements(DELETES)
