"""Added missing foreign keys. Set uuid nullable

Revision ID: 530539821085
Revises: 17e484f70dba
Create Date: 2015-10-07 20:46:50.987432

"""

# revision identifiers, used by Alembic.
revision = '530539821085'
down_revision = '17e484f70dba'

from alembic import op
import sqlalchemy as sa


INSERTS = """"""
DELETES = """"""


def iter_statements(stmts):
    for st in [x for x in stmts.split('\n') if x]:
        op.execute(st)


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actions', 'uuid',
               existing_type=sa.CHAR(length=32),
               nullable=True)
    op.alter_column('comments', 'uuid',
               existing_type=sa.CHAR(length=32),
               nullable=True)
    op.create_foreign_key('fk_comments_gid_usergroups', 'comments', 'usergroups', ['gid'], ['id'])
    op.create_foreign_key('fk_comments_uid_users', 'comments', 'users', ['uid'], ['id'])
    op.alter_column('forms', 'uuid',
               existing_type=sa.CHAR(length=32),
               nullable=True)
    op.create_foreign_key('fk_forms_gid_usergroups', 'forms', 'usergroups', ['gid'], ['id'])
    op.create_foreign_key('fk_forms_uid_users', 'forms', 'users', ['uid'], ['id'])
    op.alter_column('modules', 'uuid',
               existing_type=sa.CHAR(length=32),
               nullable=True)
    op.alter_column('profiles', 'uuid',
               existing_type=sa.CHAR(length=32),
               nullable=True)
    op.create_foreign_key('fk_profiles_gid_usergroups', 'profiles', 'usergroups', ['gid'], ['id'])
    op.create_foreign_key('fk_profiles_uid_users', 'profiles', 'users', ['uid'], ['id'])
    op.alter_column('roles', 'uuid',
               existing_type=sa.CHAR(length=32),
               nullable=True)
    op.create_foreign_key('fk_roles_gid_usergroups', 'roles', 'usergroups', ['gid'], ['id'])
    op.create_foreign_key('fk_roles_uid_users', 'roles', 'users', ['uid'], ['id'])
    op.alter_column('sprints', 'uuid',
               existing_type=sa.CHAR(length=32),
               nullable=True)
    op.alter_column('tags', 'uuid',
               existing_type=sa.CHAR(length=32),
               nullable=True)
    op.create_foreign_key('fk_tags_uid_users', 'tags', 'users', ['uid'], ['id'])
    op.create_foreign_key('fk_tags_gid_usergroups', 'tags', 'usergroups', ['gid'], ['id'])
    op.alter_column('tasks', 'uuid',
               existing_type=sa.CHAR(length=32),
               nullable=True)
    op.create_foreign_key('fk_tasks_gid_usergroups', 'tasks', 'usergroups', ['gid'], ['id'])
    op.create_foreign_key('fk_tasks_uid_users', 'tasks', 'users', ['uid'], ['id'])
    op.alter_column('usergroups', 'uuid',
               existing_type=sa.CHAR(length=32),
               nullable=True)
    op.create_foreign_key('fk_usergroups_gid_usergroups', 'usergroups', 'usergroups', ['gid'], ['id'])
    op.create_foreign_key('fk_usergroups_uid_users', 'usergroups', 'users', ['uid'], ['id'])
    op.alter_column('users', 'uuid',
               existing_type=sa.CHAR(length=32),
               nullable=True)
    op.create_foreign_key('fk_users_uid_users', 'users', 'users', ['uid'], ['id'])
    op.create_foreign_key('fk_users_gid_usergroups', 'users', 'usergroups', ['gid'], ['id'])
    ### end Alembic commands ###
    iter_statements(INSERTS)


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_gid_usergroups', 'users', type_='foreignkey')
    op.drop_constraint('fk_users_uid_users', 'users', type_='foreignkey')
    op.alter_column('users', 'uuid',
               existing_type=sa.CHAR(length=32),
               nullable=False)
    op.drop_constraint('fk_usergroups_uid_users', 'usergroups', type_='foreignkey')
    op.drop_constraint('fk_usergroups_gid_usergroups', 'usergroups', type_='foreignkey')
    op.alter_column('usergroups', 'uuid',
               existing_type=sa.CHAR(length=32),
               nullable=False)
    op.drop_constraint('fk_tasks_uid_users', 'tasks', type_='foreignkey')
    op.drop_constraint('fk_tasks_gid_usergroups', 'tasks', type_='foreignkey')
    op.alter_column('tasks', 'uuid',
               existing_type=sa.CHAR(length=32),
               nullable=False)
    op.drop_constraint('fk_tags_gid_usergroups', 'tags', type_='foreignkey')
    op.drop_constraint('fk_tags_uid_users', 'tags', type_='foreignkey')
    op.alter_column('tags', 'uuid',
               existing_type=sa.CHAR(length=32),
               nullable=False)
    op.alter_column('sprints', 'uuid',
               existing_type=sa.CHAR(length=32),
               nullable=False)
    op.drop_constraint('fk_roles_uid_users', 'roles', type_='foreignkey')
    op.drop_constraint('fk_roles_gid_usergroups', 'roles', type_='foreignkey')
    op.alter_column('roles', 'uuid',
               existing_type=sa.CHAR(length=32),
               nullable=False)
    op.drop_constraint('fk_profiles_uid_users', 'profiles', type_='foreignkey')
    op.drop_constraint('fk_profiles_gid_usergroups', 'profiles', type_='foreignkey')
    op.alter_column('profiles', 'uuid',
               existing_type=sa.CHAR(length=32),
               nullable=False)
    op.alter_column('modules', 'uuid',
               existing_type=sa.CHAR(length=32),
               nullable=False)
    op.drop_constraint('fk_forms_uid_users', 'forms', type_='foreignkey')
    op.drop_constraint('fk_forms_gid_usergroups', 'forms', type_='foreignkey')
    op.alter_column('forms', 'uuid',
               existing_type=sa.CHAR(length=32),
               nullable=False)
    op.drop_constraint('fk_comments_uid_users', 'comments', type_='foreignkey')
    op.drop_constraint('fk_comments_gid_usergroups', 'comments', type_='foreignkey')
    op.alter_column('comments', 'uuid',
               existing_type=sa.CHAR(length=32),
               nullable=False)
    op.alter_column('actions', 'uuid',
               existing_type=sa.CHAR(length=32),
               nullable=False)
    ### end Alembic commands ###
    iter_statements(DELETES)
