"""Added fields to sprint modul

Revision ID: 8e2197c96c5
Revises: 2ad4629b8cc5
Create Date: 2015-08-19 21:32:24.864544

"""

# revision identifiers, used by Alembic.
revision = '8e2197c96c5'
down_revision = '2ad4629b8cc5'

from alembic import op
import sqlalchemy as sa


INSERTS = """"""
DELETES = """"""


def iter_statements(stmts):
    for st in [x for x in stmts.split('\n') if x]:
        op.execute(st)


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'sprints', sa.Column('end', sa.Date(), nullable=True))
    op.add_column(u'sprints', sa.Column('start', sa.Date(), nullable=True))
    op.add_column(u'sprints', sa.Column('strength', sa.Integer(), nullable=True))
    ### end Alembic commands ###
    iter_statements(INSERTS)


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'sprints', 'strength')
    op.drop_column(u'sprints', 'start')
    op.drop_column(u'sprints', 'end')
    ### end Alembic commands ###
    iter_statements(DELETES)
